apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spa-example
  labels:
    apps.tanzu.vmware.com/workload-type: spa
    app.kubernetes.io/part-of: spa-example
spec:
  build:
    env:
    -  name: BP_NODE_RUN_SCRIPTS
       value: build
  source:
    git:
      url: https://github.com/tsalm-pivotal/tap-react-sample.git
      ref:
        branch: main
    subPath: "frontend/"